spring.datasource.url=jdbc:mysql://localhost:3306/student_tracker
spring.datasource.username=springStudent
spring.datasource.password=springStudent

spring.main.banner-mode=off

# Show only WARN and ERROR logs
logging.level.root=WARN